services:
  backend:
    build: ./backend
    container_name: p_lightgbm_backend_container
    restart: "no"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # để nhìn code trên máy, sửa code không cần build lại
      - ./backend/dataset:/app/dataset
      - ./backend/models:/app/models
  
  frontend:
    build: ./frontend
    container_name: p_lightgbm_frontend_container
    restart: "no"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules