version: "3.9"

services:
  backend:
    build: ./backend
    container_name: p_lightgbm_backend_container
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend/dataset:/app/dataset
  
  frontend:
    build: ./frontend
    container_name: p_lightgbm_frontend_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend